SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET ANSI_NULLS ON;
SET NOCOUNT ON;


USE AdventureWorks2022;

DECLARE @MinPrice DECIMAL(10,2)=1000.00;
SELECT ProductID, Name, ListPrice 
FROM Production.Product
WHERE ListPrice>@MinPrice;


